- hosts: all

  tasks:
    - name: install docker
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker
      become: yes
      tags: install

    - name: install pip
      import_role:
        name: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose
      become: yes
      tags: install

    - name: start redmine
      community.docker.docker_container:
        image: redmine:latest
        name: redmine
        pull: true
        restart: true
        ports:
          - "80:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_USERNAME: "{{ db_user }}"
          REDMINE_DB_PASSWORD: "{{ db_user_password }}"
      tags: start

- hosts: webservers

  tasks:
    - name: install datadog
      import_role:
        name: datadog.datadog
      vars:
        datadog_site: "datadoghq.eu"
        datadog_api_key: "{{ datadog_api_keys_dict[inventory_hostname] }}"
      become: yes
      tags: install-datadog
